name: CI Checks

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          git submodule update --checkout
          cd tools/CMock
          git submodule update --init vendor/unity
          cd ../..
          sudo apt-get install -y lcov
          cmake -S test/unit-test -B test/unit-test/build/ \
          -G "Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_FLAGS='--coverage -Wall -Wextra -DNDEBUG'
          make -C test/unit-test/build/ all
      - name: Test
        run: |
          cd test/unit-test/build/
          ctest -E system --output-on-failure
          cd ..
      - name: Coverage
        run: |
          make -C test/unit-test/build/ coverage
          lcov --rc lcov_branch_coverage=1 --remove test/unit-test/build/coverage.info '*test*' --output-file test/unit-test/build/coverage.info
          lcov --rc lcov_branch_coverage=1 --remove test/unit-test/build/coverage.info '*CMakeCCompilerId*' --output-file test/unit-test/build/coverage.info
          lcov --rc lcov_branch_coverage=1 --remove test/unit-test/build/coverage.info '*third-party*' --output-file test/unit-test/build/coverage.info
          lcov --rc lcov_branch_coverage=1 --remove test/unit-test/build/coverage.info '*mocks*' --output-file test/unit-test/build/coverage.info
          lcov --list test/unit-test/build/coverage.info
      #- name: lcov-cop
      #  uses: ChicagoFlutter/lcov-cop@v1.0.2
      #  with:
      #    path: "build/coverage.info"
      #    min_coverage: 99
      #    exclude: "**/*test*"
    
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify
      - name: Run Uncrustify
        run: find . -iname "*.[hc]" -exec uncrustify --check -c tools/uncrustify.cfg {} +
      - name: Check For Trailing Whitespace
        run: |
          set +e
          grep --exclude="README.md" -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            exit 1
          else
            exit 0
          fi
